// <auto-generated />
namespace ChalkIt.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Exercise_Migration_changeFromAuthorToCoursesCollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exercise_Migration_changeFromAuthorToCoursesCollection));
        
        string IMigrationMetadata.Id
        {
            get { return "201212262328492_Exercise_Migration_changeFromAuthorToCoursesCollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
